### ISSUE TITLE
Idea: Save event photographs here

### ISSUE THREAD

**Issue by vog** [berlin-hack-and-tell/berlinhackandtell.rocks#107]
Just a rough idea: As we are "freeing" information from the Meetup Forum to this page, what about the photographs? Does it make sense to copy them over here, too?

(Then, replacing the "Photos" links with local links to this site, where all photographs of the respective BHNT event are listed.)

@stefanhoth, @ligi: What do you think?

**Comment by stefanhoth** [comment]
Fine with me. It's not a crazy amount of data. Should be fine.

**Comment by ligi** [comment]
:+1: rescue all the data!
