### ISSUE TITLE
Add information from poll of BHNT#51

### ISSUE THREAD

**Issue by vog** [berlin-hack-and-tell/berlinhackandtell.rocks#164]
Woever did the poll for BHNT#51: Could you copy & paste your data into this issue, please?

Then, others (such as myself) could take care of incorporating it.

The only important thing is that we have the data here.

**Comment by ligi** [comment]
Not sure how to reach Simon - he was making the poll/list - do you have the contact @stefanhoth ?

**Comment by stefanhoth** [comment]
I had another look and I actually found it.

Cketti - Extensible Family Emoji
Markus - Pitch Detect
Knuth - GitHub Licence Check
Adam - Berlinale NOW
Michael - MapSCII (Maps + ASCII)
Seid - Apartment Snake
David - JS Test Visualizer 2000 Gold
Riot - Hack this box


Winner: Michael - MapSCII (Maps + ASCII)

**Comment by vog** [comment]
Great. Thanks! Now we just need a volunteer to put that into the site, and perhaps searching/guessing some URLs.
