### ISSUE TITLE
Moving domains to berlinhackandtell.rocks

### ISSUE THREAD

**Issue by stefanhoth** [berlin-hack-and-tell/berlinhackandtell.rocks#186]
This is just an FYI for @ligi @vog etc

Given that the US-based people for `hackandtell.org` are so unreliable and hard to reach I moved the project to ´berlinhackandtell.rocks´ to keep it alive.

I also changed the repo name and all occurrences I could find. 

If I manage to get contact to any domain owner I will try to revive `berlin.hackandtell.org´ as a forward to the new domain. No promises though.

**Comment by stefanhoth** [comment]
PS: Update your local remotes if you still have a local checkout somewhere.

**Comment by vog** [comment]
Renamed my directories, my forked repository and adjusted my `.git/config`.

@stefanhoth Thanks for taking care of that.

The whole domain `hackandtell.org` was down for quite some time. External dependencies are always critical, and unreliable ones are especially risky.

In case we are able to make them revive `berlin.hackandtell.org`, I propose not to rename everything again. Instead, we should simply ask them to create an HTTP(S) redirect from `berlin.hackandtell.org` to `berlinhackandtell.rocks`.

BTW, I like the new domain `berlinhackandtell.rocks`, but I hope it isn't too expensive. I suppose that `berlinhackandtell.de` would have been much cheaper.

**Comment by stefanhoth** [comment]
>  Instead, we should simply ask them to create an HTTP(S) redirect 
Yes, that's what I meant to say. 

> but I hope it isn't too expensive
I was surprised to learn it's the same price of the .de domain (at least at Hetzner)

**Comment by stefanhoth** [comment]
Also PS: I purchased a mail forwarder. Which should be the address? `mail@` or `team@` ? Something else?

**Comment by vog** [comment]
My 2 cents:

Either `mail@...` because this is so common and simple and can easily be guessed.

Or, use a more unique identifier (e.g. `bhnt-team`) to prevent spam, i.e. to avoid spambots which probe "generic name" @ "domain" for many domains.

I'm don't like `team@` as it combines the disadvantages of both.

**Comment by vog** [comment]
@ligi What do you think?

**Comment by ligi** [comment]
mail@ sounds good - but have no strong opinion on that - currently quite busy

**Comment by stefanhoth** [comment]
@ligi @vog I set up the mail forward that now pipes into a Google group. If you let me know a Google-account I will add it to this Group so you'd get the messages to this address, too.

**Comment by stefanhoth** [comment]
@ligi still need your gmail account to be added to the Google Group.

**Comment by stefanhoth** [comment]
Done. ✅
