### ISSUE TITLE
Better layout/editing: Use jekyll data sources and post layouts

### ISSUE THREAD

**Issue by stefanhoth** [berlin-hack-and-tell/berlinhackandtell.rocks#187]
Knowing jekyll's features just a bit I know we could leverage either data sources or posts to make navigation of the page and the layout a bit more user friendly. This would allow to link to "episodes" directly instead of one big list.

**Comment by stefanhoth** [comment]
This is mainly to not forget about the idea for an improvement.

**Comment by stefanhoth** [comment]
I've done this over the weekend.
This is a slight spoiler and I'll send a proper PR soon.
![image](https://user-images.githubusercontent.com/45467/32148988-845f6d50-bcfe-11e7-9ae9-838983c9082f.png)

**Comment by stefanhoth** [comment]
👀 @ligi @vog

**Comment by ligi** [comment]
looks nice

**Comment by vog** [comment]
Good work!
