### ISSUE TITLE
Explain what hack and tell is

### ISSUE THREAD

**Issue by k-nut** [berlin-hack-and-tell/berlinhackandtell.rocks#220]
Should we maybe explain what hack and tell is on the website? Right now it's just a collection of the hacks but maybe we could add a short paragraph at the top to explain to newcomers what they are looking at? That way we could link to that page to explain to people what BHNT is instead of having to link to the Meetup page.

What do you all think?

**Comment by ligi** [comment]
> What do you all think?

love the idea - that said I will realistically have no time to work on this any time soon ..

**Comment by vog** [comment]
@k-nut That's a very good idea. In case you'd like to draft such a paragraph, please go ahead.

**Comment by lucasrangit** [comment]
@ligi you can close this. it's been merged.
