### ISSUE TITLE
Add slides for Berlin Hack & Tell #72 - "Electing Hacks"

### ISSUE THREAD

**Issue by qabbasi** [berlin-hack-and-tell/berlinhackandtell.rocks#250]
👋 I was one of the speakers of the above meetup. It would be great if you could add slides to https://berlinhackandtell.rocks/

**Comment by qabbasi** [comment]
c.f. https://www.meetup.com/Berlin-Hack-and-Tell/events/261731520/

**Comment by stefanhoth** [comment]
Done via #249

**Comment by stefanhoth** [comment]
Sorry, we've added the slides but the list of hacks is still missing. @lucasrangit would you be able to add that?

**Comment by lucasrangit** [comment]
Yes, I'll do it now.
