### ISSUE TITLE
bhnt 72 add hacks

### ISSUE THREAD

**Issue by lucasrangit** [berlin-hack-and-tell/berlinhackandtell.rocks#254]
1. AFL
1. webRTC beaker 
1. dotfile rage by chr6stpr
1. Quadrobot
1. DebLib by Henry addo 
1. Crypto yield curve by Max
1. Hexliterate by ssimono
1. Infinito by KevinFranz

**Comment by D1plo1d** [comment]
My github for webRTC beaker and associated 3D printer hacks is `https://github.com/tegh`. Thanks for an awesome event :)

**Comment by lucasrangit** [comment]
> My github for webRTC beaker and associated 3D printer hacks is `https://github.com/tegh`. Thanks for an awesome event :)

 @D1plo1d  Do you mean https://github.com/D1plo1d/tegh-cli ? Your link is broken.

**Comment by D1plo1d** [comment]
@lucasrangit sorry about that it's moved to https://github.com/tegapp/
