### ISSUE TITLE
bhnt 73 hacks

### ISSUE THREAD

**Issue by lucasrangit** [berlin-hack-and-tell/berlinhackandtell.rocks#257]
| 1 PycturePlanner by GorgiAstro | 2 Zpkg by ihucos | 3 Lovebits by murimuffin5 | 4 Feedly replacement by Knut | 5 Game of life by Lucasrangit | 6 Overload by yro | 7 1D cellular automata ne By subgraph | 8 Shakyground by |

**Comment by ligi** [comment]
thanks! here some more notes from victor:

#73 07-2019

1. PycturePlanner
@gorgiastro
gh:gorgiastro/my-first-pyside2-orekit-gui
PySide + Orekit

2. zpkg
@ihucos
"meta package manager
zpkg.plash.io
gh:ihucos/zpkg

3. LoveBits
@Murat Kemaldar
"code poems
lovebits.bilebile.net

4. selfhosted RSS in DNS
@Knut
reader.k-nut.eu CNAME dynDNS A IP
miniflux.app
!filler

5. Interview
@Lucas Rangit
"Conway's Game of Life
gh:lucasrangit/interview
ncurses, gcc

6. overload
@Yro
git.finnendahl.de/Yro/overload
Python, Pascal, function overloading

7. one dimensional cellular automata
Python, Steven Wolfram
!spontaneous demo

8. shakemap
earth quake, ISO lines, Python, LeafletJS, Vue, NodeJS

**Comment by ligi** [comment]
we need to double check the github handles here I just saw - e.g. I know @knut -> @k-nut

**Comment by ligi** [comment]
hack of the month was: LoveBits

**Comment by lucasrangit** [comment]
Anyone know the presenter names for the last two?
