### ISSUE TITLE
News BHNT 75

### ISSUE THREAD

**Issue by MarlonSchultz** [berlin-hack-and-tell/berlinhackandtell.rocks#267]
# NEWS

- [Meetup.com Introduces RSVP Fees for Members, WordPress Meetup Groups Unaffected by Pricing Changes](https://wptavern.com/meetup-com-introduces-rsvp-fees-for-members-wordpress-meetup-groups-unaffected-by-pricing-changes)

- [Docker Hub gets 2FA](https://www.docker.com/blog/designing-docker-hub-2fa/)

- [Django 3.0 released](https://www.djangoproject.com/weblog/2019/oct/14/django-30-beta-1-released/)

**Comment by vog** [comment]
* IOCCC 2019 winner programs finally released: https://www.ioccc.org/years.html#2019

**Comment by lucasrangit** [comment]
Thanks for the news. Let's save it for next month when you are feeling better and can present. I
already have a bunch of news slides about open hardware.
