### ISSUE TITLE
News / Hosting BHNT 76

### ISSUE THREAD

**Issue by MarlonSchultz** [berlin-hack-and-tell/berlinhackandtell.rocks#270]
# Hosting
Who will be around to help? @ligi is in Japan and @lucasrangit is in the States.

I will be there and can host. Some help / Co-Moderation would be great.

# MateLight

@lucasrangit built a new system to control the matelight. It will have its maiden voyage next week. Plus: The speaker will be able to see the countdown on a seperate screen. 

# News
@vog is still news worthy to you ? "IOCCC 2019 winner programs finally released: https://www.ioccc.org/years.html#2019" I think it has not been mentioned last time by @lucasrangit 

- Kotlin 1.3.6 has been released
- Github Actions && packet registry are generally available.
- Docker has been purchased by Mirantis
- Go has turned 10. 
- Rust 1.39 now supports asynch && await

Please add news.

**Comment by MarlonSchultz** [comment]
Oh, we need a TITLE !!!!

**Comment by vog** [comment]
I believe the IOCCC 2019 winner notification is still worth mentioning, especially with regard to encourage everyone to participate in next year's 2020 round of IOCCC.

I originally wanted to present my IOCCC entry at this BHNT, but will probably postpone this again, as I promised to ligi to present when he's back. That way, mentioning IOCCC this in in slides, and next time in terms of my presentation, might be a good fit, to keep mentioning IOCCC and hence to motivate more people to participate next year.

**Comment by vog** [comment]
News (from October, but not mentioned last time, I think):

* Nobel prize to Michel Mayor and Didier Queloz "for the discovery of an exoplanet orbiting a solar-type star". https://www.nobelprize.org/prizes/physics/2019/summary/

Related title proposals:

* Exo Hacks
* Exo(planetary) Hacks

**Comment by ligi** [comment]
cool you will host the BHNT @MarlonSchultz ! looking forward to seeing the new counter system when I am back.

Title suggestion: "CyberHacks" - as the CyberTruck was just released by tesla

the Kotlin version is actually 1.3.60

I think the stuff from the github universe is quite nice - the new search functions, semantic code nav and the github archive program
https://twitter.com/mr_ligi/status/1194673505872203776
https://twitter.com/mr_ligi/status/1194779760901021697
also perhaps mention 36c3 - e.g. with this: https://twitter.com/Bleeptrack/status/1197616698519629824

fun fact here (c++ author dislikes Bitcoin written in c++): https://twitter.com/pavolrusnak/status/1194393639461494784

have a great BHNT!

**Comment by MarlonSchultz** [comment]
KK, ill announce it later today via Twitter and Meetup.

**Comment by MarlonSchultz** [comment]
I will add a small RIP for Jimmy Schulz at the beginning.

**Comment by lucasrangit** [comment]
Thanks for hosting Marlon! Looking forward to seeing the hacks and
pictures.
