### ISSUE TITLE
Presentations of BHNT#79?

### ISSUE THREAD

**Issue by vog** [berlin-hack-and-tell/berlinhackandtell.rocks#299]
BHNT#80 will start soon, but the BHNT#79 hacks aren't yet on the website.

I remember that those were collected in the pad at: https://pad.systemli.org/p/bhnt079

However, that one has been emptied in the meantime.

* Does anyone else have a backup/copy of this?
* Alternatively, what about the list of hacks from the voting?

**Comment by ligi** [comment]
started a PR here: #302
