### ISSUE TITLE
Proposal: Second set of slides

### ISSUE THREAD

**Issue by vog** [berlin-hack-and-tell/berlinhackandtell.rocks#312]
I propose to create a second set of slides to be shown before and during the break after the 4th presentation.

* The first slide would have a "Flea market" headline and a quick summary of the flea market rules (line up, 1-2 sentences, etc.)
  * It would be shown only during the flea market.
* The second slide would point to Lucas' small bottles project.
* The third and final slide would be shown during the whole break, containing just 3 bullet points:
  * Asking the audience to bring their bottles to the bar.
  * Asking the presenters-so-far to contribute to the presentation list of the pad, repeating the pad URL (https://pad.systemli.org/p/bhnt082), maybe including a QR code.
  * Showing the end time of the break. (Since that is a dynamic during value the event, it could be realized by a large `<input>` field injected into Markdown, to be filled in live on stage while the slide is shown. Alternatively, the organizer could edit and rebuild the slides, but I imagine this to be quite cumbersome to do live on stage.)

My questions:

1. Would that make sense to you?
2. How would we include these slides? Separate file? Add to the end of the existing slides? Other ideas?

**Comment by ligi** [comment]
great idea - would just put them to the normal slides - we also have the voting slide there as this is only shown on the end we can do the same with the "in-between-slide"

**Comment by vog** [comment]
Okay, pull request provided. Two remarks on that:

1. Please note especially the input field at "Until"
2. I was using inline styling to fix some issues. Feel free to convert them into a custom SCSS file if you think this is appropriate.
3. @lucasrangit Feel free to fill in the "Help Lucas!" section and/or to add some picture as you see fit.

**Comment by vog** [comment]
Okay, pull request provided. Some remarks on that:

1. I edited the existing slides for BHNT#81, so it will serve as a proper template for the upcoming BHNT#82.
2. Please note especially the input field after "Until" ;-)
3. I was using inline styling to fix some issues. Feel free to convert them into a custom SCSS file if you think this is appropriate.
4. @lucasrangit Feel free to fill in the "Help Lucas!" section and/or to add some picture as you see fit.

**Comment by vog** [comment]
Changing assignee to @lucasrangit for my final question:

@lucasrangit Please adjust the "Help Lucas!" section as you see fit.

**Comment by lucasrangit** [comment]
Fixed by #319
