### ISSUE TITLE
Proposal: Recreate Gemfile.lock to fix dependabot#2

### ISSUE THREAD

**Issue by vog** [berlin-hack-and-tell/berlinhackandtell.rocks#313]
I can't see any easy way to fix that one security alert:

* https://github.com/berlin-hack-and-tell/berlinhackandtell.rocks/security/dependabot/2

I'd propose to just remove Gemfile.lock, rebuild everything (so an up-to-date Gemfile.lock is generated from the Gemfile), and see if everything still works. This "flight forward" is probably the easiest way forward, compared to carefully upgrading only the minimum amount of dependencies.

What do you think?

**Comment by lucasrangit** [comment]
> SGTM - actually had big problems with the deps when doing the slides - the FFI dep really made problems and cost me some time

@ligi , where you using the Docker container and still having issues?

**Comment by Hasona1991** [comment]
> لا يمكنني رؤية أي طريقة سهلة لإصلاح تنبيه الأمان هذا:
> 
> * https://github.com/berlin-hack-and-tell/berlinhackandtell.rocks/security/dependabot/2
> 
> أقترح فقط إزالة Gemfile.lock ، وإعادة بناء كل شيء (لذلك يتم إنشاء Gemfile.lock محدث من Gemfile) ، ومعرفة ما إذا كان كل شيء لا يزال يعمل. ربما تكون "الرحلة إلى الأمام" أسهل طريقة للمضي قدمًا ، مقارنةً بالترقية الدقيقة فقط للحد الأدنى من التبعيات.
> 
> ماذا تعتقد؟

#304
