### ISSUE TITLE
Add information from Google Docs polls

### ISSUE THREAD

**Issue by vog** [berlin-hack-and-tell/berlinhackandtell.rocks#54]
Add information from previous Google Docs polls.

See also: https://github.com/berlin-hack-and-tell/berlin-hack-and-tell.github.io/pull/6#issuecomment-278802011

**Comment by stefanhoth** [comment]
Could someone help me please? I have a list of polls in my drive folder but I don't have time right now to go through all of them and compare with the website. I'll post a list of events I have information of and you tell me which content you need.

- 5
- 7
- 11
- 22
- 24
- 26
- 27
- 29
- 30
- 31
- 32
- 33
- 35
- 38
- 43
- 44
- 45
- 46
- 47
- 48

Sorry I can't do more.

**Comment by vog** [comment]
Making a TODO list out of your items, so we can mark all unneeded and/or incorporated entries:

- [ ] 5
- [ ] 7
- [ ] 11
- [ ] 22
- [ ] 24
- [ ] 26
- [ ] 27
- [ ] 29
- [ ] 30
- [ ] 31
- [ ] 32
- [ ] 33
- [ ] 35
- [ ] 38
- [ ] 43
- [ ] 44
- [ ] 45
- [ ] 46
- [ ] 47
- [ ] 48

**Comment by vog** [comment]
Okay, with #119 finally the picture is complete and we know exactly which information from Google Docs poll we need, and which ones we don't need.

**Comment by stefanhoth** [comment]
Closing this as all listed issues are either resolved or closed otherwise.

That was great team work! Thanks 🎉
