### ISSUE TITLE
Add information from Google Docs polls for BHNT#43

### ISSUE THREAD

**Issue by vog** [berlin-hack-and-tell/berlinhackandtell.rocks#61]
This is the first request regarding #54.

For BHNT#43 we were only able to reconstruct 2 presentations:

* https://berlin-hack-and-tell.github.io/#berlin-hack-and-tell-43---easter-heggs

@stefanhoth Which were the remaining ones?

**Comment by stefanhoth** [comment]
Web of Science Scraper by Alia	
CloudRunner by Sebastian
Parallel Reversal Schedules by Volker
Live Counter by Knut	
Slate by Mario (Oreo)	
Docker/Swarm by Jerome
Jekyll by Ligi	

Hack of the month: Double Sided QR by Aleksei

**Comment by vog** [comment]
Reopening, as this information still needs to be incorporated into README.md.

**Comment by vog** [comment]
@stefanhoth Are you sure this information is correct? I'm pretty sure that I won the throphy (for the first and only time in BHNT at all) when presenting tool I developed for my math diploma thesis "prs".

**Comment by ligi** [comment]
Hm I just wanted to add a link to my presentation after reviewing and merging the change - but then saw that this entry already exists - AFAIR I was only taling about jekyll / jekyllify once and it was after I presented the survival manual app - so this entry must be wrong

**Comment by vog** [comment]
@stefanhoth That would be the 2nd error in this Google Docs poll dataset. This is really strange.

Anyway, I'd suggest that we simply fix all mistakes that we find.

**Comment by ligi** [comment]
yea - but the only fix I have in mind currently is just to remove it -
but then it would be 7 slots - strange - think I will look into this
later - was mainly a reminder to not forge this and maybe get some
external info on this ..

**Comment by vog** [comment]
@ligi Leaving this issue open as a reminder for you. :-)

**Comment by vog** [comment]
@ligi Any progress on this?

**Comment by vog** [comment]
@ligi I think we should be some decision here to get this off the table.

**Comment by vog** [comment]
@ligi Any progress on this?

This is the last "historical" issue regarding the incorporation of the old Google Docs polls. If we don't resolve this now, we'll probably never resolve it.

**Comment by vog** [comment]
@ligi What about you? You mentioned in your comment https://github.com/berlin-hack-and-tell/berlinhackandtell.rocks/issues/61#issuecomment-289793713 that you might get some external info on this.

**Comment by ligi** [comment]
Yea - this was my hope - that perhaps a participant was reading the issue and could fill the gap. Unfortunately not the case and I also have no idea ..

**Comment by vog** [comment]
Okay, so let's close this issue as non-resolvable.
